AllCops:
  TargetRubyVersion: 2.5.1

Metrics/BlockLength:
  Max: 50
  Exclude:
    - '**/*.gemspec'

Metrics/LineLength:
  Max: 120

Style/SafeNavigation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
