AllCops:
  TargetRubyVersion: 2.5.1

Metrics/LineLength:
  Max: 120

Style/SafeNavigation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/Documentation:
  Enabled: false
