AllCops:
  TargetRubyVersion: 2.5.1

Metrics/BlockLength:
  Max: 50
  Exclude:
    - '**/*.gemspec'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 250

Style/SafeNavigation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/AlignHash:
  EnforcedColonStyle: table

Layout/EndOfLine:
  EnforcedStyle: lf

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/UnneededSort:
  Enabled: false

Security/MarshalLoad:
  Enabled: false
